---
# yaml-language-server: $schema=https://kubernetes-schemas.${SECRET_DOMAIN}/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-hd
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-hd-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # PUSHOVER_TOKEN, SONARR__API_KEY
        key: sonarr-hd
    - extract:
        # PUSHOVER_USER_KEY
        key: pushover
