---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: kube-system
spec:
  provider:
    onepassword:
      connectHost: http://scorpion.${SECRET_PRIVATE_DOMAIN}:8080
      vaults:
        Production: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-secret
            key: token
            namespace: kube-system
