---
kubernetes:
  children:
    master:
      hosts:
        k8s-control-prod-0:
          ansible_host: 10.10.1.10
        k8s-control-prod-1:
          ansible_host: 10.10.1.11
        k8s-control-prod-2:
          ansible_host: 10.10.1.12
    worker:
      hosts:
        k8s-worker-prod-3:
          ansible_host: 10.10.1.13
        k8s-worker-prod-4:
          ansible_host: 10.10.1.14
