---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-radarr-uhd
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-rook-ceph-cluster
  path: ./kubernetes/apps/default/radarr-uhd/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: radarr-uhd
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
