apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:BTeirzi+zIkRHT2lf4SovvJZis03DP0ChkKGdnUFYJ7LuWHv3Q9dnGM2lDn0BGlMNI0rnB8xyMQ+AWfp,iv:RYnPIySCDgoCyjzXwSMUWKdtwU53GGNu/bJDDafyiek=,tag:asMM4UBhPRDLddeyy1qvsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbE9wUVRPb0NISVd3eGdh
            cFNrVEc0UDNKeHF0aytCL0ZQYUdTWlJRS1YwCmZWSUlEenpjODZlOGNPTWVCa3VO
            WUJPYk9TQU1HZFo1ejg4YkZkdGZWdTQKLS0tIHRvc1ZJUjNZSkloTUR1WG03YjhS
            eklTc0QwTTA0bkNqZGFwRmpkMm96cHMK7/yXvNI+WOupT9sdNOiLBYsrC87867f3
            cQiITjRhq0KwEEhU9v/5VdkV+Knu2SjtJn9KogVtdw93nm7iLc7HuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-07T12:52:21Z"
    mac: ENC[AES256_GCM,data:vxzw3oA6M9xFwPAOhS2N4LtiGMHu1VVs+vstHxSXxLY4I4TltbS/JIK7UwRDdfIOPeqG7PHJxAq2AR/1NHayuSgN7JxR1Y0aXFKtUiNiuua83iRULk5uLxMMROrv4Yp1Q0E8SIB2YoS6LesNB27ryEI9wdN7199zE8nNNajt8vA=,iv:xALIEc0PRsHj0XYLFsg1RUat8o03ZM4E/wdIWbqHvFg=,tag:VQV5fLE/nqSdpsxnO9Hy1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
