---
apiVersion: v1
kind: ConfigMap
metadata:
  name: letsblockit-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: letsblockit
        group: public
        url: https://letsblockit.prymal.info/list/091c0d79-9b5b-4682-a052-9a195fed2b26.txt
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 401"
          - "[BODY] == Unauthorized"
        alerts:
          - type: discord
