---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kube-prometheus-stack-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        DISCORD_WEBHOOK_URL: "{{ .DISCORD_WEBHOOK_URL }}"
  dataFrom:
    - extract:
        key: discord
