apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:aRWJ3eTGzKBHy7A=,iv:eetVGNWuyzLRDCMSl2gP1Nei3aOLOvpzss0j/mOYk5M=,tag:nG7sKbfcFVl6GCiXOlSuKg==,type:str]
    SECRET_BASE_DN: ENC[AES256_GCM,data:Xm/pSyoiBkkih/Saxk8z/Po=,iv:A7S+d/k9gtEsQr1Lp1JziLlD3j2qW2V32W/jWblViK4=,tag:Z9FDYjhCB4U/h2fX44h9qg==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:b62PLpVdHswLFiC0,iv:EQnZgRzz6TKa8cTN32IVAxAYKRNdrHCif7+6+uEG87E=,tag:w9QNjEPerIsTNUl6Lb7yHQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:/xHqGd7Nv2aFWYriSDK9xDjoEjk=,iv:GAMy0zl8CyT4XWpI3Q1k48f6UEy8swnpoe07Qv6rCqU=,tag:W9SKGUmwjhLgCzrSqbti4w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:cJk5K3xHuZoKFb2XB7jO6WzrRV52QbD9xTlTpWeff4LZqDlL,iv:KRvHU60tqUd0ZlbSMuRmM2RpekunCb261DJsQG5NPeo=,tag:YcVUnf6jepJ63VqauxPjAQ==,type:str]
    SECRET_PROMETHEUS_DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:MVg5YFUz4/God3HbmyaVVW0hk/vyGoT7eZtdfEuVatusWtzrYHpXsKRdgMa0WY1Lujha7oOylx/SaDH2B4yAC4q/npnHnUZssPNx9xqk9tRHL0arHG2QFHl4AQKsnwikiNftH1lulB6Qsu61eT4G7b05PbnxXpVjzzMC,iv:nw4myMs6nDXd96tT03QVA8FRi+z0WJmZBLDSP9rxfbA=,tag:4CbSc58+6U0MYZqQ3/11Jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bWVjTFp5SllTNFBXWGVo
            alJwNVRsc0FJUm9ZcjNOWFFUdVZ6ZmE1UHdjClc1ZnNIcjVtaEVDK1B6T2R5Z3Av
            dGhLL3lzRVp0eVNLUXppamp5MzlCNzgKLS0tIGZaaFZnVUw2SjVsRW9zY254RkhY
            V0JkSUhSb2Ivc01hRmpBQktFbHMxZ2sKlcTa3VhOo2j2c0XAwwXXjaqYReLh85RW
            mtvYHIktgtHGVmDAeyzCbhNXyxqyqG9v8DYhO/fY1c45cJmgyb2+2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-24T14:55:45Z"
    mac: ENC[AES256_GCM,data:J4k0UYdUjzR6NDS8Xty27www0ReAx0gypekeP2cC5BA1wQCbmVKlLBCYy8AnBAnz5d/6p2FtUl+IebEUZfeAPNZqwTVIg6ewr8eU5AZTvfAgXmKpFcixaft9WQL+fcxuZ5dDOF/MYf+kfC3ancvs0MEgiFJOMtyhPGVkJ8m3+Pw=,iv:8SkGmKtSjpZMDCqOiYzVCcpx9vDx47bjFvmm2GIxTUc=,tag:sG+v+BrWo99jvbSM32FrDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
