apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:aRWJ3eTGzKBHy7A=,iv:eetVGNWuyzLRDCMSl2gP1Nei3aOLOvpzss0j/mOYk5M=,tag:nG7sKbfcFVl6GCiXOlSuKg==,type:str]
    SECRET_BASE_DN: ENC[AES256_GCM,data:Xm/pSyoiBkkih/Saxk8z/Po=,iv:A7S+d/k9gtEsQr1Lp1JziLlD3j2qW2V32W/jWblViK4=,tag:Z9FDYjhCB4U/h2fX44h9qg==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:b62PLpVdHswLFiC0,iv:EQnZgRzz6TKa8cTN32IVAxAYKRNdrHCif7+6+uEG87E=,tag:w9QNjEPerIsTNUl6Lb7yHQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:/xHqGd7Nv2aFWYriSDK9xDjoEjk=,iv:GAMy0zl8CyT4XWpI3Q1k48f6UEy8swnpoe07Qv6rCqU=,tag:W9SKGUmwjhLgCzrSqbti4w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:cJk5K3xHuZoKFb2XB7jO6WzrRV52QbD9xTlTpWeff4LZqDlL,iv:KRvHU60tqUd0ZlbSMuRmM2RpekunCb261DJsQG5NPeo=,tag:YcVUnf6jepJ63VqauxPjAQ==,type:str]
    SECRET_DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:y44P8VRAVG2rZ0h0NoCigDpwtA95J+zgH0KgLzLdTn1ZYmxudorzo5ZdCL5n+SRsSw4NsRRFZqHIdoFIX37bz2sPLP22Ri2IRpeDhRAvgcVxUKaGcap32OE5VVww10hFc6+6hcw4h0rUsw4jNZkka4IV3Np3ZqiI4ZEN/g==,iv:OhIUiK6xuRIu3c+bm12tAUt1rRUztQJDcReP+g+8YVQ=,tag:8aT2yvtrjHsUBCdYX2XOAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bWVjTFp5SllTNFBXWGVo
            alJwNVRsc0FJUm9ZcjNOWFFUdVZ6ZmE1UHdjClc1ZnNIcjVtaEVDK1B6T2R5Z3Av
            dGhLL3lzRVp0eVNLUXppamp5MzlCNzgKLS0tIGZaaFZnVUw2SjVsRW9zY254RkhY
            V0JkSUhSb2Ivc01hRmpBQktFbHMxZ2sKlcTa3VhOo2j2c0XAwwXXjaqYReLh85RW
            mtvYHIktgtHGVmDAeyzCbhNXyxqyqG9v8DYhO/fY1c45cJmgyb2+2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-24T14:48:10Z"
    mac: ENC[AES256_GCM,data:8e3o+eni/ZGRHSHXkyLZ4uUByhIJba+Q+bEukCjDQbOqPqBqJ55OybYNKmcDS97FA+86mjMJn1uiPZtcsAzHWzQ1wJIVF5H3lw/txg3NttRurogovCD6YG4p0/S2cnekqLrgERoE1XqTLZ/Mo2RLbgZpAe6Gl5QLmP/KW0LFINM=,iv:QdE2ifxcVrU9mClLFZd54s5TKhhoXpOeSx4TLnzXc4A=,tag:URh/GdLBfRmFsXn1ESUTUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
