---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/objectbucket.io/objectbucketclaim_v1alpha1.json
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: thanos-bucket-v1
  namespace: monitoring
spec:
  bucketName: thanos-v1
  storageClassName: ceph-bucket
