---
# yaml-language-server: $schema=https://kubernetes-schemas.${SECRET_DOMAIN}/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: semaphore
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: semaphore-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        SEMAPHORE_DB_USER: &dbUser "{{ .SEMAPHORE_DB_USER }}"
        SEMAPHORE_DB_PASS: &dbPass "{{ .SEMAPHORE_DB_PASS }}"
        SEMAPHORE_DB_HOST: &dbHost postgres-rw.database.svc.cluster.local
        SEMAPHORE_DB_PORT: "5432"
        SEMAPHORE_DB_DIALECT: postgres
        SEMAPHORE_DB: semaphore
        SEMAPHORE_ADMIN_PASSWORD: "{{ .SEMAPHORE_ADMIN_PASSWORD }}"
        SEMAPHORE_ADMIN_NAME: admin
        SEMAPHORE_ADMIN_EMAIL: admin@localhost
        SEMAPHORE_ADMIN: admin
        SEMAPHORE_ACCESS_KEY_ENCRYPTION: "{{ .SEMAPHORE_ACCESS_KEY_ENCRYPTION }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: semaphore
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: semaphore
    - extract:
        key: cloudnative-pg
